# Generated by Django 6.0.3 on 2026-03-12 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rank', models.CharField(choices=[('final-user', 'Final User'), ('sysadmin', 'Sysadmin'), ('finance', 'Finance')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.functionaluser')),
                ('address', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
            ],
        ),
    ]
