# Generated by Django 6.0.3 on 2026-03-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='preferences',
            field=models.TextField(blank=True, help_text='Sèries i gèneres preferits'),
        ),
    ]
