# Generated by Django 6.0.4 on 2026-04-14 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_infouser_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name_attempted', models.CharField(blank=True, db_index=True, help_text='Nombre de usuario introducido en el intento fallido.', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP del cliente en el momento del intento.', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User-Agent del navegador/cliente.', max_length=512)),
                ('reason', models.CharField(blank=True, help_text="Motivo del fallo: 'wrong_password', 'user_not_found', etc.", max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Intento de login fallido',
                'verbose_name_plural': 'Intentos de login fallidos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MovieImageOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(db_index=True, help_text="ID de la pel·lícula/sèrie tal com el retorna l'API externa.", max_length=50, unique=True)),
                ('title', models.CharField(blank=True, help_text="Títol de referència (no afecta la lògica, és per llegibilitat a l'admin).", max_length=255)),
                ('manual_image', models.ImageField(blank=True, help_text="Imatge manual que substitueix qualsevol imatge de l'API. Format recomanat: 16:9 (ex. 1280×720px).", null=True, upload_to='movie_overrides/')),
                ('notes', models.TextField(blank=True, help_text="Notes internes sobre aquest override (no es mostren a l'usuari).")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Override d'imatge de pel·lícula",
                'verbose_name_plural': "Overrides d'imatge de pel·lícules",
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='functionaluser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': 'Información de usuario', 'verbose_name_plural': 'Información de usuarios'},
        ),
        migrations.AddField(
            model_name='functionaluser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='functionaluser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desactiva este usuario para bloquearlo sin eliminarlo.'),
        ),
        migrations.AddField(
            model_name='functionaluser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='functionaluser',
            name='rank',
            field=models.CharField(choices=[('final-user', 'Usuario Final'), ('sysadmin', 'Administrador'), ('finance', 'Finanzas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='preferences',
            field=models.TextField(blank=True, help_text='Géneros cinematográficos seleccionados (mínimo 5)'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='sex',
            field=models.CharField(choices=[('male', 'Hombre'), ('female', 'Mujer')], max_length=10),
        ),
    ]
