# Generated by Django 6.0.4 on 2026-04-15 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_harden_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiFailureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(db_index=True, max_length=100)),
                ('base_url', models.URLField(blank=True, max_length=255)),
                ('operation', models.CharField(db_index=True, max_length=100)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error_type', models.CharField(db_index=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('response_excerpt', models.TextField(blank=True)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Incidencia de API',
                'verbose_name_plural': 'Incidencias de APIs',
                'ordering': ['-last_seen', '-timestamp'],
            },
        ),
    ]
