# Generated by Django 6.0.4 on 2026-04-15 10:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_apifailureevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='apifailureevent',
            name='severity',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], db_index=True, default='medium', max_length=10),
        ),
        migrations.CreateModel(
            name='ContentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('movie', 'Película'), ('series', 'Serie')], db_index=True, max_length=10)),
                ('content_id', models.CharField(db_index=True, max_length=50)),
                ('interaction_type', models.CharField(choices=[('view', 'Visualización'), ('favorite_add', 'Añadir a favoritos'), ('favorite_remove', 'Quitar de favoritos')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(blank=True, db_index=True, max_length=100)),
                ('platform_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_interactions', to='web.functionaluser')),
            ],
            options={
                'verbose_name': 'Interacción de contenido',
                'verbose_name_plural': 'Interacciones de contenido',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('movie', 'Película'), ('series', 'Serie')], db_index=True, max_length=10)),
                ('content_id', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('platform_name', models.CharField(blank=True, max_length=150)),
                ('platform_url', models.URLField(blank=True)),
                ('content_image_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='web.functionaluser')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'content_id'), name='favoritecontent_unique_per_user_content')],
            },
        ),
    ]
